### ISSUE TITLE
Feat: Neve FSE parent theme V1

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/neve-fse#1]
### Setup
This theme will become a parent theme.
This will be our full Neve FSE integration.

### What do we want to achieve?
- [x] Have a full implementation of FSE with the Neve name
    - [x] Have the designs/styles/ ready for how the theme should look and feel. #3
    - [x] Create themeisle.com page, store product, set up the process release, etc. #24 
    - [x] Create the new theme under the `development` branch.
    - [x] More controls for Typography variations #5
- [ ] Inherit styles from Customizer from existing non-FSE Neve theme.
   - [ ] Migrating Neve customizer options on install #2
- [ ] Ensure compatibility with the Neve PRO plugin Codeinwp/neve-pro-addon#2420
- [x] Release

We will link and track all other related issues to this one.
Once every checklist item is completed we should have a full FSE implementation for Neve.

**Comment by preda-bogdan** [comment]
@JohnPixle there are no files at the moment. We will copy the structure from one of our FSE themes.
The files from this repository are for the child Neve theme with hybrid support for FSE, this will be replaced by the full FSE theme.

The files will be under the `development` branch.

Do you require these files to get started on the design?

**Comment by preda-bogdan** [comment]
@JohnPixle Thank you for the update, will try to have them ready by the end of the week and ping you back when I add them.

**Comment by mghenciu** [comment]
Thank you @preda-bogdan for the setup. 

If I remember correctly, when we worked on the other FSE themes - Andrei did setup an action (not 100% that's the technical term) that builds the theme zip on push.
I think that would help for this case also, so we can add the changes and be able to test how those look on a live site.

**Comment by preda-bogdan** [comment]
@mghenciu The action is present when you open a PR it will create a build with the theme each time you push new changes to that PR. You can fork from `development`.

@JohnPixle I've updated the `development` branch and we now inherit the colors defined in Neve prior to switching the theme to Neve FSE. I would appreciate if you can let me know what do you think about the current mapping:

```
"color": {
      "palette": [
        {
          "slug": "ti-bg",
          "color": "var(--nv-site-bg, #FFFFFF)",
          "name": "Background"
        },
        {
          "slug": "ti-fg",
          "color": "var(--nv-text-color, #202020)",
          "name": "Foreground"
        },
        {
          "slug": "ti-bg-alt",
          "color": "var(--nv-light-bg, #EDEAE4)",
          "name": "Background Alt"
        },
        {
          "slug": "ti-bg-inv",
          "color": "var(--nv-dark-bg, #1A1919)",
          "name": "Background Dark"
        },
        {
          "slug": "ti-fg-alt",
          "color": "var(--nv-text-dark-bg, #FBFBFB)",
          "name": "Foreground Alt"
        },
        {
          "slug": "ti-accent",
          "color": "var(--nv-primary-accent, #435DEB)",
          "name": "Accent"
        }
      ],
      "link": true,
      "gradients": []
    },
```

You can test this using the development branch as these changes are already present there.

For the fonts I don't know that we can import any font, but we can decide on a few that if present we will use. Let me know your thoughts.

Thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle Thank you for confirming the mapping. I've updated the branch with all 6 of your style variations and the respective fonts.

The workflow is the following:
1. The inherited color values will only apply to the default style which is a copy of the first style for all purposes with the addition of having values inherited from neve.
2. The other variations will not inherit any colors from Neve.

I propose that we will only inherit a font if it is one of the fonts that are already present on the theme, what do you think?

Next, I'll start adding the layout elements to look the same as the Web Agency SS from Neve.

Let me know if you guys have any thoughts or feedback, thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle Thank you for the response. I've updated your instance with the latest development build. You can see all the changes I mentioned there.

Let me know if you require anything else.
